image: golang

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  - export CURRENT_BUILD_PATH=$(pwd)
  - rm -rf $HOME/gopath
  - mkdir -p $HOME/gopath/src/git.nulana.com/bobrnor/battleship-server
  - export GOPATH=$HOME/gopath
  - export PATH=$PATH:$GOPATH/bin
  - echo $PATH
  - go version
  - go env
  - which go
  - git clone git@git.nulana.com:bobrnor/sqlsugar.git
  - git clone git@git.nulana.com:bobrnor/json-ep.git

test:
  script:
    - cp -R $CURRENT_BUILD_PATH/* $HOME/gopath/src/git.nulana.com/bobrnor/battleship-server
    - cd $HOME/gopath/src/git.nulana.com/bobrnor/battleship-server
    - go get ...
    - go test ./...
